// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFYVKFnUAUEo4Wx9_vnV8nZuhl-0MssX0',
    appId: '1:613618748931:android:8c34fdf856280b9199c836',
    messagingSenderId: '613618748931',
    projectId: 'birthday-app-f6d90',
    databaseURL: 'https://birthday-app-f6d90-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'birthday-app-f6d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwnTyd_Db_eo6XfsbSxHXb_2LffsUaUA',
    appId: '1:613618748931:ios:4d20dd3b5d9415d899c836',
    messagingSenderId: '613618748931',
    projectId: 'birthday-app-f6d90',
    databaseURL: 'https://birthday-app-f6d90-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'birthday-app-f6d90.appspot.com',
    iosBundleId: 'com.example.birthdayApp',
  );
}
